# Use postgres/example user/password credentials
version: '3.1'

services:
  rabbitmq:
    container_name: "rabbitmq"
    restart: unless-stopped
    build:
      context: ./RDIPs-Gateway
      dockerfile: Broker.Dockerfile
    environment:
      - RABBITMQ_ERLANG_COOKIE=/var/lib/rabbitmq/.erlang.cookie
      - RABBITMQ_CONFIG_FILES=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_MNESIA_BASE=/var/lib/rabbitmq/mnesia
      - RABBITMQ_LOG_BASE=/var/log/rabbitmq
      - RABBITMQ_ENABLED_PLUGINS_FILE=/etc/rabbitmq/enabled_plugins
    ports:
      - '5672:5672'
      - '15672:15672'
      - '1883:1883'
    volumes:
      - './:/var/lib/rabbitmq'
    networks:
      - pi4
  gateway:
    container_name: "gateway"
    build:
      context: ./RDIPs-Gateway
      dockerfile: Gateway.Dockerfile
    ports:
      - '1000:1000'
    volumes:
      - './:/var/lib/gateway'
    networks:
      - pi4
  db:
    container_name: postgres
    env_file:
      - .env
    image: postgres
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - pi4
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9090:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - pi4
    links:
      - db:sunflower
  api:
    container_name: sunflower_api
    build:
      context: ./RDIPs-BE
      dockerfile: Dockerfile
      target: production
    depends_on:
      - db
    ports:
      - '8080:8080'
    links:
      - db:sunflower
    volumes:
      - './:/srv/www/volume_sunflower'
    networks:
      - pi4
volumes:
  db:
  pgadmin:
  api:
networks:
  pi4:
    driver: bridge
