# Use postgres/example user/password credentials
version: '3.1'

services:
  rabbitmq:
    container_name: "rabbitmq"
    restart: unless-stopped
    # command: tail -F /dev/null
    build:
      context: ./RDIPs-Gateway
      dockerfile: Broker.Dockerfile
    environment:
      - RABBITMQ_ERLANG_COOKIE=/var/lib/rabbitmq/.erlang.cookie
      - RABBITMQ_CONFIG_FILES=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_MNESIA_BASE=/data/mnesia
      - RABBITMQ_LOG_BASE=/data/log
      - RABBITMQ_ENABLED_PLUGINS_FILE=/etc/rabbitmq/enabled_plugins
    ports:
      - '5672:5672'
      - '15672:15672'
      - '1883:1883'
    networks:
      pi4:
        aliases:
          - sfBroker
  gateway:
    container_name: "gateway"
    # Maybe there some memory leak that prevent docker to excute command so this is good for now
    # entrypoint: ["./bin/RDIPs-Gateway"]
    entrypoint: ["tail", "-f", "/dev/null"]
    build:
      context: ./RDIPs-Gateway
      dockerfile: Gateway.Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - rabbitmq
    volumes:
      - './RDIPs-Gateway:/var/lib/gateway'
    # command: ["/bin/sh", "-c", "tail -F /dev/null"]
    networks:
      pi4:
        aliases:
          - sfBroker
  db:
    container_name: postgres
    env_file:
      - .env
    image: postgres
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      pi4:
        aliases:
          - sunflower
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9090:80"
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      pi4:
        aliases:
          - sunflower
  api:
    container_name: sunflower_api
    build:
      context: ./RDIPs-BE
      dockerfile: Dockerfile
      target: production
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - './RDIPs-BE:/srv/www/volume_sunflower'
    networks:
      pi4:
        aliases:
          - sunflower
volumes:
  db:
  pgadmin:
  api:
networks:
  pi4:
    driver: bridge
