# Use postgres/example user/password credentials
version: '3.1'

services:
  keycloak:
    container_name: "keycloak"
    image: quay.io/keycloak/keycloak:23.0.1
    ports:
      - "9091:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/auth/realms/master"]
      interval: 10s
      retries: 5
      start_period: 20s

  rabbitmq:
    container_name: "rabbitmq"
    restart: unless-stopped
    # command: tail -F /dev/null
    build:
      context: ./RDIPs-Gateway
      dockerfile: Broker.Dockerfile
    environment:
      - RABBITMQ_ERLANG_COOKIE=/var/lib/rabbitmq/.erlang.cookie
      - RABBITMQ_CONFIG_FILES=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_MNESIA_BASE=/data/mnesia
      - RABBITMQ_LOG_BASE=/data/log
      - RABBITMQ_ENABLED_PLUGINS_FILE=/etc/rabbitmq/enabled_plugins
    ports:
      - '5672:5672'
      - '15672:15672'
      - '1883:1883'
    healthcheck:
          test: rabbitmq-diagnostics -q ping
          interval: 30s
          timeout: 30s
          retries: 3
    networks:
      pi4:
        aliases:
          - sfBroker
  # gateway:
  #   container_name: "gateway"
  #   # Maybe there some memory leak that prevent docker to excute command so this is good for now
  #   # entrypoint: ["./bin/RDIPs-Gateway"]
  #   entrypoint: ["tail", "-f", "/dev/null"]
  #   build:
  #     context: ./RDIPs-Gateway
  #     dockerfile: Gateway.Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - rabbitmq
  #   volumes:
  #     - './RDIPs-Gateway:/var/lib/gateway'
  #   # command: ["/bin/sh", "-c", "tail -F /dev/null"]
  #   networks:
  #     pi4:
  #       aliases:
  #         - sfBroker
  db:
    container_name: postgres
    env_file:
      - .env
    image: postgres
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      pi4:
        aliases:
          - sunflower
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9090:80"
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      pi4:
        aliases:
          - sunflower
  api:
    container_name: sunflower_api
    env_file:
      - .env
    build:
      context: ./RDIPs-BE
      dockerfile: Dockerfile
      target: production
    depends_on:
        db:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy
        keycloak:
          condition: service_healthy

    ports:
      - '8080:8080'
    volumes:
      - './RDIPs-BE:/srv/www/volume_sunflower'
    networks:
      pi4:
        aliases:
          - sunflower
volumes:
  db:
  pgadmin:
  api:
networks:
  pi4:
    driver: bridge
