FROM golang:1.24.0-alpine3.21 AS go-base

WORKDIR /app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .
RUN go build -o app

FROM python:3.10-slim AS python-base
WORKDIR /model
COPY ./model/ .
RUN pip install torch
RUN pip install pyinstaller
RUN pip install -r requirements.txt
RUN pyinstaller --onefile main.py

FROM alpine:3.23.2 AS production
WORKDIR /app
COPY --from=go-base /app/app .
COPY --from=python-base /model/dist/main ./model/main
CMD ./model/main & ./app
