proxy_cache_path /var/cache/nginx
                    keys_zone=NginxCache:20m
                    inactive=60m
                    levels=1:2
                    max_size=10g;

# Default rate limit
# Each limit only take 10 megabyte with rate 10 limit per sec or each within 100ms
limit_req_zone $binary_remote_addr zone=defLimit:10m rate=10r/s;

include /opt/nginx/conf.d/app.conf;
include /opt/nginx/conf.d/keycloak.conf;
include /opt/nginx/conf.d/store.conf;