proxy_cache_path /var/cache/nginx
                    keys_zone=NginxCache:20m
                    inactive=60m
                    levels=1:2
                    max_size=10g;

# Default rate limit
# Each limit only take 10 megabyte with rate 10 limit per sec or each within 100ms
limit_req_zone $binary_remote_addr zone=defLimit:10m rate=10r/s;

server {
    server_name www.sunflower-rdips.tech sunflower-rdips.tech;
    listen 80;
    listen 443 ssl;

    ssl_certificate /etc/nginx/client.crt;
    ssl_certificate_key /etc/nginx/client.key;
    ssl_dhparam /etc/nginx/dhparam.pem;

    # proxy_cache NginxCache;
    root /usr/share/nginx/html/sunflower;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        set $backend_api "http://sunflower_api:8080";

        limit_req zone=defLimit burst=20 nodelay;
        proxy_pass $backend_api;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; #forward client ip address to server
        proxy_set_header HOST $host;
        # proxy_cache_methods GET;
        # proxy_cache_valid 200 10m;
        rewrite ^/api/?(.*) /$1 break;
        proxy_redirect     off;
        add_header Access-Control-Allow-Origin *;
        # add_header X-Proxy-Cache $upstream_cache_status; # check if we are using cache or not
    }

    access_log /var/log/nginx/default_access.log;
    error_log  /var/log/nginx/default_error.log; # Health check notifications
}

server {
    listen 9000 ssl;
    listen 80;
    listen 443 ssl;

    ssl_certificate /etc/nginx/client.crt;
    ssl_certificate_key /etc/nginx/client.key;
    ssl_dhparam /etc/nginx/dhparam.pem;

    # proxy_cache NginxCache;
    server_name www.auth.sunflower-rdips.tech auth.sunflower-rdips.tech;

    location / {
        set $kc "https://auth.sunflower-rdips:8443";

        proxy_pass $kc; #pass to upstream demo
        proxy_set_header Host $host;
        proxy_buffers 4 16k;
    }

    access_log /var/log/nginx/default_access.log;
    error_log  /var/log/nginx/default_error.log; # Health check notifications
}
