server {
    listen 9000 ssl;

    ssl_certificate /etc/nginx/client.crt;
    ssl_certificate_key /etc/nginx/client.key;
    ssl_dhparam /etc/nginx/dhparam.pem;

    # proxy_cache NginxCache;
    server_name www.auth.sunflower-rdips.tech auth.sunflower-rdips.tech;

    location / {
        set $kc "https://auth.sunflower-rdips:8443";

        proxy_pass $kc;
        proxy_set_header Host $host;
        proxy_buffers 4 16k;
    }

    access_log /var/log/nginx/default_access.log;
    error_log /var/log/nginx/default_error.log; # Health check notifications
}
