server {
    listen 80;

    location /_postgrest {
        internal;
        default_type application/json;
        proxy_hide_header Content-Location;
        add_header Content-Location /api/$upstream_http_content_location;
        proxy_set_header Connection "";
        proxy_http_version 1.1;
        proxy_pass http://postgrest:3000/;
    }

    location /_memcached {
        internal;
        # Map the query parameter '?key=abc' to the Memcached key
        set $memc_key $arg_key;

        # Map an optional expiration parameter '?exptime=60' (defaults to 0 / never expire)
        set $memc_exptime $arg_exptime;

        # Map HTTP Methods to Memcached commands
        if ($request_method = POST) {
            set $memc_cmd set;
        }
        if ($request_method = GET) {
            set $memc_cmd get;
        }
        if ($request_method = DELETE) {
            set $memc_cmd delete;
        }
    }
}