tunnel: f1dd4cc9-6721-45a9-9c77-c326f4e4945a
credentials-file: /home/hieu/.cloudflared/f1dd4cc9-6721-45a9-9c77-c326f4e4945a.json

ingress:
  - hostname: api.sunflower-rdips.tech
    service: http://localhost:80

  - hostname: amqp-management.sunflower-rdips.tech
    service: http://localhost:81

  - hostname: mqtt.sunflower-rdips.tech
    service: http://localhost:1883

  - hostname: amqp.sunflower-rdips.tech
    service: http://localhost:5672


  - service: http_status:404
