tunnel: bd21bef4-1139-4b0a-be2f-df8887380661
credentials-file: /home/hieu/.cloudflared/cert.pem

ingress:
  - hostname: sunflower-rdips.tech
    service: http://localhost:80

  - hostname: amqp-management.sunflower-rdips.tech
    service: http://localhost:81

  - hostname: mqtt.sunflower-rdips.tech
    service: http://localhost:8883

  - hostname: amqp.sunflower-rdips.tech
    service: http://localhost:8672

  - hostname: auth.sunflower-rdips.tech
    service: http://localhost:9000

  - service: http_status:404
