log_format rabbitmq '$remote_addr [$time_local] $protocol $status $bytes_received ' 
                '$bytes_sent $upstream_addr';

upstream rabbitmq_mqtt {
    server mqtt.sunflower-rdips:8883;
}

upstream rabbitmq_amqp {
    server amqp.sunflower-rdips:5671;
}

server {
    listen 8883 ssl;
    proxy_pass rabbitmq_mqtt;
    ssl_certificate /etc/nginx/client.crt;
    ssl_certificate_key /etc/nginx/client.key;

    access_log /var/log/nginx/mqtt_access.log rabbitmq;
    error_log  /var/log/nginx/mqtt_error.log; # Health check notifications
}

server {
    listen 8672 ssl;
    proxy_pass rabbitmq_amqp;
    ssl_certificate /etc/nginx/client.crt;
    ssl_certificate_key /etc/nginx/client.key;

    access_log /var/log/nginx/amqp_access.log rabbitmq;
    error_log  /var/log/nginx/amqp_error.log; # Health check notifications
}
