log_format rabbitmq '$remote_addr [$time_local] $protocol $status $bytes_received '
'$bytes_sent $upstream_addr';

server {
    listen 8883;

    set $mqtt_target "mqtt.sunflower-rdips:8883";
    proxy_pass $mqtt_target;

    access_log /var/log/nginx/mqtt_access.log rabbitmq;
    error_log /var/log/nginx/mqtt_error.log;
}

server {
    listen 8672;

    set $amqp_target "amqp.sunflower-rdips:5671";
    proxy_pass $amqp_target;

    access_log /var/log/nginx/amqp_access.log rabbitmq;
    error_log /var/log/nginx/amqp_error.log;
}